### ISSUE TITLE
aarch64-darwin: nix build .#compactc fails — chez's llvmPackages_18 stdenv compiles compiler-rt-libc-18 against libcxx 21 (apple-sdk 26.5)

### ISSUE THREAD

**Issue by patextreme** [MediaNoxLabs/compact#85]
### Summary

On `aarch64-darwin`, building the Nix `compactc` package fails after the nixpkgs bump in #69. The darwin `chez` override pins `stdenv = pkgs.llvmPackages_18.stdenv`, but compact's pinned nixpkgs now pairs that LLVM-18 toolchain with the top-level `libcxx-21.1.6+apple-sdk-26.5` headers. clang-18 does not implement the builtins libc++ 21 uses, so `compiler-rt-libc-18.1.8` fails to compile and the failure cascades to `chez-scheme` → `compactc`.

`main`/`develop` are unaffected (they still lock the pre-#69 nixpkgs); `codegen-rust` and anything branched after #69 are broken.

### Environment

- System: `aarch64-darwin` (GitHub `macos-latest` / `macos-15`; also local Apple Silicon)
- compact ref: `codegen-rust` @ `611a3dda0c512326a2c15a2e68ce20f8dcf58105` (and any rev after #69, incl. `e7297f33d9b0`)
- compact's nixpkgs pin: `c27cdad491a991b11ed731760aa2ef8db0cb0410` (2026-08-27)
- Last working nixpkgs pin: `bcc4a9d9533c033d806a46b37dc444f9b0da49dd` (2026-02-18)

### Reproduction

```bash
# on aarch64-darwin, against codegen-rust (or any post-#69 rev)
nix build .#compactc
# equivalently, entering a shell that includes compactc:
nix develop .#compiler --command compactc --version
```

Also reproduced downstream by a consumer whose devshell includes `compact.packages.${system}.compactc`:
https://github.com/MediaNoxLabs/midnight-identity/actions/runs/34848690795/job/103993813619 (`Test macos-latest`).

### Actual behaviour

```
error: Cannot build '...-compiler-rt-libc-18.1.8.drv'.
  .../libcxx-21.1.6+apple-sdk-26.5/include/c++/v1/__bit/countr.h:28:10:
      error: use of undeclared identifier '__builtin_ctzg'
  .../include/c++/v1/bitset:487:32:
      error: no matching function for call to '__countr_zero'
  .../include/c++/v1/__charconv/traits.h:98:23:
      error: no matching function for call to '__countl_zero'
  10 errors generated.
```

Failure chain: `compiler-rt-libc-18.1.8` → `clang-wrapper-18.1.8` → `stdenv-darwin` → `chez-scheme-10.4.1` → `compactc` → `nix-shell-env` (all "1 dependency failed").

### Root cause

`flake.nix` (line ~104 on `codegen-rust`; same binding on `main`/`develop`):

```nix
isDarwin = pkgs.lib.hasSuffix "-darwin" system;
chez = if isDarwin then pkgs.chez.override {
  stdenv = pkgs.llvmPackages_18.stdenv;
} else pkgs.chez;
```

On darwin the LLVM-18 stdenv's C++ standard library resolves to the **top-level** `libcxx` (apple-sdk 26.5 / libc++ 21) rather than `llvmPackages_18.libcxx`. clang-18 lacks the C++ builtins libc++ 21 assumes (`__builtin_ctzg`/`__builtin_clz*` family), so `compiler-rt-libc` cannot build.

The override itself predates this — it was already present and working at `afec3cf75a9a6eff717a275cb3820cbf0bc60c27` (2026-08-11) with the older nixpkgs.

### When it broke

| commit | date | compact nixpkgs | darwin `compactc` |
|---|---|---|---|
| `afec3cf75a9a` | 2026-08-11 | `bcc4a9d9533c` (2026-02-18) | builds |
| `d131ac0fda04` | 2026-08-31 | `bcc4a9d9533c` (2026-02-18) | builds |
| **`c9743367a`** (first commit of #69) | **2026-09-07** | **`c27cdad491a9` (2026-08-27)** | **first broken** |
| `10dd2242a` (#69 merged) | 2026-09-08 | `c27cdad491a9` | broken |

#69 was an intentional nixpkgs bump to fix crates.io 403s on Linux; the darwin breakage is collateral.

### Why CI didn't catch it

No workflow builds the Nix `compactc` package on macOS:

- `build-compiler.yml` — `ubuntu-latest` only (this is where `nix build .#compactc` / `nix develop .#compiler --command compactc ...` run).
- `compact-test.yml` macOS matrix (`macos-15`, `macos-latest`) — bare `cargo build` / `cargo nextest`, no Nix.
- `rust-runtime-test.yml` macOS matrix — explicitly "no nix build"; its Nix-compactc job is `ubuntu-latest`.

So the darwin Nix path has been unexercised since the nixpkgs bump and rotted silently.

### Suggested fixes (pick one)

1. Keep LLVM 18 but make its libc++ consistent — thread `pkgs.llvmPackages_18.libcxx` (or the matching `apple-sdk`) into the overridden stdenv so `compiler-rt-libc` no longer sees libc++ 21 headers.
2. Use the nixpkgs-matched default: `stdenv = pkgs.llvmPackages.stdenv;` — only if the LLVM-18 pin isn't load-bearing for `chez` on darwin (it was presumably added because a newer clang broke the chez build, so verify).
3. Bump/re-lock nixpkgs to a revision where `llvmPackages_18` and `apple-sdk` are consistent, retaining the #69 crates.io fix.

Plus: add a macOS (or at least darwin-evaluating) Nix job that builds `.#compactc`, so this can't regress again.

### Consumer workarounds (until fixed)

- Pin compact to a pre-#69 rev (`afec3cf75a9a` or earlier) — loses the #69 crates.io fix.
- Don't pull `compactc` into darwin devshells / CI shells.
- Override compact's nixpkgs input to a fixed revision from the consumer flake.
